language: ruby
sudo: false
rvm: 2.3.3
cache: [bundler, apt]
git:
  depth: 1

# CMake 2.8.9 or higher is required
# https://github.com/gjtorikian/commonmarker/blob/099344c91805000b0253f8aecbb96c38dfa95b9c/.travis.yml
addons:
  apt:
    sources:
      - kalakris-cmake
    packages:
      - cmake

script: bundle exec rake

notifications:
  webhooks:
    - https://idobata.io/hook/6a98db40-ac68-45ec-a1b4-d8dd5851c2e3
