language: ruby
sudo: false
rvm: 2.3.1
cache: [bundler, apt]

addons:
  apt:
    packages:
      - libicu-dev

script: bundle exec rake

notifications:
  webhooks:
    - https://idobata.io/hook/6a98db40-ac68-45ec-a1b4-d8dd5851c2e3
